# Generated by Django 5.2.2 on 2025-06-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('limpieza', 'Limpieza'), ('reforestacion', 'Reforestación'), ('reciclaje', 'Reciclaje'), ('educacion', 'Educación Ambiental'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='recursoeducativo',
            name='categoria_material',
            field=models.CharField(choices=[('articulo', 'Artículo'), ('video', 'Video'), ('infografia', 'Infografía'), ('otro', 'Otro')], default='otrorecurso', max_length=100),
        ),
    ]
