# Generated by Django 5.2.2 on 2025-06-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('limpieza', 'Limpieza'), ('reforestacion', 'Reforestación'), ('reciclaje', 'Reciclaje'), ('educacion', 'Educación Ambiental'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
